name: build-and-publish-repo

on:
  push:
    branches: [ master ]
  workflow_dispatch:

#permissions:
#  contents: write

jobs:
  build:
    runs-on: ubuntu-24.04
#    env:
#      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
      - name: Checkout source
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Install build deps
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential debhelper devscripts fakeroot \
            reprepro dpkg-dev lintian

      - name: Build packages
        run: |
          set -euo pipefail
          rm -rf out
          mkdir -p out

          shopt -s nullglob
          for d in */ ; do
            if [ ! -f "$d/debian/control" ]; then
              continue
            fi

            echo "Building $d"
            (
              cd "$d"
              dpkg-buildpackage -us -uc -b
            )

            cp -v ./*.deb ./*.dsc ./*.tar.* ./*.changes ./*.buildinfo ./out/ 2>/dev/null || true

          done

      # reprepro does not understand the 'all' architecture specification
      # specifically list all published arches instead. https://serverfault.com/questions/279153/
      - name: Initialize reprepro repo
        run: |
          mkdir -p repo/conf
          cat > repo/conf/distributions <<'EOF'
          Origin: GitHub
          Label: Leggewie GitHub APT Repo
          Suite: stable
          Codename: generic
          Architectures: amd64 arm64 armhf
          Components: main
          Description: PPA-like repository built from GitHub Actions
          SignWith: 104C6DC95DD59599A96FD9F82777C04CF040B50D
          EOF

      - name: Import GPG signing key
        run: |
          mkdir -p ~/.gnupg
          chmod 700 ~/.gnupg
          echo "$REPO_SIGNING_KEY" | gpg --batch --import
        env:
          REPO_SIGNING_KEY: ${{ secrets.REPO_SIGNING_KEY }}

      - name: Configure gpg-agent for signing
        run: |
          cat > ~/.gnupg/gpg-agent.conf <<'EOF'
          allow-loopback-pinentry
          EOF
          gpgconf --kill gpg-agent || true

      - name: Import packages
        run: |
          set -euo pipefail
          shopt -s nullglob

          for deb in out/*.deb; do
            reprepro -b repo includedeb generic "$deb"
          done

          for dsc in out/*.dsc; do
            reprepro -b repo includedsc generic "$dsc"
          done

          rm -Rf ./repo/conf/ ./repo/db/ || true

      - name: Publish to gh-pages branch
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./repo
          publish_branch: gh-pages
